[env:wt32-eth01]
platform = espressif32@6.12.0
board = wt32-eth01
framework = arduino
build_flags =
  -D ETH_PHY_TYPE=ETH_PHY_LAN8720
  -D ETH_PHY_ADDR=1
  -D ETH_PHY_MDC=23
  -D ETH_PHY_MDIO=18
  -D ETH_CLK_MODE=ETH_CLOCK_GPIO0_IN
  -D ETH_PHY_POWER=16
